apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
  namespace: argocd
spec:
  generators:                          //Argonun Git i nasıl tarayacağını belirliyoruz//
    - git:
        repoURL: https://github.com/Ismaililica/argocd-example-apps.git
        revision: master
        directories:
          - path: "*"     // Her klasörü bir application yap//
  template:               // Keşfedilecek her klasör için üretilecek ArgoCd Application Şablonu
    metadata:
      name: 'app-{{path.basename}}'  // Değişkeni keşfedilen klasörün adını otomatik alır //
    spec:
      project: default
      source:
        repoURL: https://github.com/Ismaililica/argocd-example-apps.git
        targetRevision: master
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}' // Her uygulamayı kendi adındaki namespace e kur diyoruz //
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      
