apiVersion: argoproj.io/v1alpha1"
kind: Application
metadata:
  name: root-aps-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ismaililica/argocd-example-apps.git
    targetRevision: master
    path: apps
    helm:
      valueFiles:
        -values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
