apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      containers:
      - name: guestbook-ui
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
